version: '3'

services:
  app:
    restart: always
    container_name: MRPL
    environment:
      - TZ=Asia/Makassar
    build:
      context: -
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8005 --workers 2
